# Generated by Django 3.2 on 2021-04-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_name',
            new_name='project_names',
        ),
    ]
